config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  get 'home/next'
  get 'home/calc'
  get 'home/support'
  get 'home/organizer'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def next
  end

  def calc
  end

  def organizer
  end

  def support
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1> Regulamin 2019 </h1>


<ol>
<li> Cel zawodów.
  <br/>
  Zawody zostały stworzone w celu promocji chodzenia po górach, odkrywaniu nowych miejsc i czerpania przyjemności z trasy.  Wyzwanie dla każdego,  czy ma żelazną kondycję czy woli rozkoszować się spacerem i robić zdjęcia na trasie. Dla wyjadaczy i amatorów, dla studentów i rodzin z dziećmi. Każdy jest mile widziany, każdy może wziąć udział i mamy nadzieję, że dobrze się bawić
</li>
<li> Organizator. <b>Irracjonalnie Maszerujący</b> w osobach
  <ol type="a">
    <li>Stanisław Zawadzki, </li>
    <li>Łukasz Butkiewicz, </li>
  </ol>
<li> Miejsce i data zawodów
  <ol type="a">
  <li> Krążownik nie ma stałego miejsca startu.  Co roku impreza będzie zaczynać w innym miejscu,  tak by uczestnicy mogli poznać nowe miejsca i nowe trasy.  Miasto startu zawsze będzie spełniało dwa kryteria -  był w miarę dobry dojazd z różnych miejsc Polski i przynajmniej dwa szlaki w góry.</li>
  <li> Edycja 2019 odbędzie się w <b>Jeleniej Górze i okolicach. Start i meta będą znajdować przy kampingu Park na ulicy Sudeckiej 42a.</b> Miasta przemyslane na kolejne edycje: Wałbrzych,  Duszniki Zdrój,  Wisła,  Węgierska Gorka,  Nowy Targ,   Szczawnica Zdrój,  Krynica Zdrój, inne. kolejność oczywiście jeszcze nieustalona :)</li>
  <li> Termin  08.06-09.06 w godzinach od około 10:00 w sobotę do 18:00 w niedzielę (w przypadku opóźnienia startu przesuniemy też odpowiednio limit) - łącznie 32h</li>
  <li> Godzina startu powinna być skorelowana z dojazdem komunikacji z jakiegoś większego miasta (w przypadku Jeleniej Góry będzie to Wrocław). Więc w przypadku innych miast może to być inna godzina</li>
  <li> Po zawodach dla chętnych będzie możliwy nocleg. Dla chętnych i wytrzymałych planowana jest impreza 🙂</li>
  </ol>
</li>
<li> Trasa zawodów
  <ol type="a">
  <li><b>Nie ma żadnej oficjalnej trasy. Każdy uczestnik sam wybiera którędy i dokąd idzie,  kiedy i na ile robi przerwy.</b>  Jedynymi pewnymi punktami trasy jest start i meta oraz czas jaki można na trasę przeznaczyć.</li>
  <li>Trasa uczestników będzie weryfikowana na podstawie pomiarów GPS, lub podawana przez użytkowników i weryfikowana zdjęciami lub przez innych uczestników</li>
  <li>Zaleca się poruszanie po wyznaczonych szlakach turystycznych, szczególnie w przypadku braku rejestratora GPS</li>
  <li>O wyniku końcowym decydują nie kilometry, lecz punkty.O punktach więcej w dalszych punktach regulaminu</li>
  <li><b>Na starcie lub zakończeniu imprezy uczestnik może jeden raz skorzystać z komunikacji zbiorowej.</b> Czyli np. wsiąść w autobus do Karpacza i swoją przygodę zacząć tam. Kilometry przebyte oczywiście się wówczas nie liczą. Dzięki temu uczestnik ma większą swobodę w doborze trasy, a jednocześnie w przypadku niespodziewanego kryzysu może lepiej dostosować swój plan. Oczywiście uczestnik nie musi skorzystać z tej opcji. Koszt przejazdu pokrywany jest przez uczestnika. Trasy dojścia z dworca PKP/PKS na metę nie wliczamy do trasy</li>
  <li>Z Jeleniej Góry można wyjść trzema trasami -  na północny zachód w stronę malowniczej Doliny Bobru i schroniska Perła Zachodu,  na wschód w kierunku Rudaw Janowickich w kierunku Sokolików i na południe do Karkonoszy.</li>
</ol>
</li>
<li>Uczestnictwo
  <ol type="a">
  <li> <b>Uczestnik startuje na własną odpowiedzialność. Uczestnicy mlodsi niż 18 lat startują na odpowiedzialność rodziców i całą imprezę muszą być pod opieką osoby dorosłej.</b></li>
  <li> Limit w edycji 2019 wynosi 40 osób.</li>
  <li> Zapisy kończą sie na tydzień przed zawodami. No gora trzy dni 🙂 Ale serio, na miejscu nie dopiszemy, dajcie znać chociaż dzień wcześniej. Nie jest to oficjalna impreza, więc nikogo nie pogonimy, ale dla spokoju organizacyjnego lepiej byśmy mieli listę uczestników wcześniej.</li>
  <li> Jeśli musisz zrezygnować z wyjścia, też nas poinformuj jak najszybciej. W przypadku nie stawienia się na starcie o czasie, możesz zacząć później, ale po uprzednim powiadomieniu telefonicznym organizatorów</li>
  <li> Dojazd na imprezę i noclegi przed i po są w gestii uczestników.  Organizator może pomóc, ale nie jest do tego zobligowany. </li>
  <li> Nie ma pakietow startowych, punktów żywieniowych, biletow do KPNu - wszystko załatwić trzeba samemu. Chętnie udzielimy porad i informacji</li>
  </ol></li>

<li> Obowiązki i prawa organizatora
  <ol type="a">

  <li> Organizator może nieznacznie zmienić godziny i miejsce startu i mety w zależności od czynników losowych</li>
  <li> Organizator może w każdej chwili zadzwonić do uczestnika, jeśli ów podał mu swój numer telefonu, by dowiedzieć się na temat miejsca, formy i stanu zawodnika. Działa to w drugą stronę - zawsze można zadzwonić do któregoś z organizatorów w istotnych kwestiach.</li>
  </ol></li>
<li> Obowiązki i prawa uczestnika
  <ol type="a">

  <li> <b>Uczestnik zobowiązuje się przestrzegać wszelkich praw i przepisów dotyczących chodzenia po górach, po lasach i terenach prywatnych.</b> Impreza jest nieoficjalna, czyli nie mamy żadnych dodatkowych praw jakich nie mają osoby indywidualne wędrujące po górach.</li>
  <li> Uczestnik we własnym zakresie organizuje posiłki,  odpoczynki, ewentualne noclegi, sprzęt. Dopuszczalna jest pomoc osób z zewnątrz oraz korzystanie ze sklepów,  restauracji, schronisk.</li>
  <li> Zdecydowanie zalecane jest posiadania <b>dzialajacego i dzwoniacego telefonu</b> oraz zameldowania, jeśli nie pojawi się na mecie. Podanie tego numeru jest również zalecane aby móc zapewnić bezpieczeństwo uczestników</li>
  <li> <b>W przypadku jakichkolwiek kontuzji i sytuacji zagrożenia zdrowia lub życia należy poinformować odpowiednie służby (GOPR,  pogotowie) oraz organizatora.</b> W razie kontuzji nie zagrażających zdrowiu najpierw dzwonić do organizatorów.</li>
  <li> Ubezpieczenia zawodnicy organizują na własną rękę, jeśli uznają to za konieczne</li>
  <li> Uczestnik musi korzystać z wlasnych map. Urządzenia GPS są dozwolone. Przed zawodami zamieścimy orientacyjna mape z punkami bonusowymi</li>
  <li> Uczestnik ma  obowiązek  dotrzeć na metę do dwóch godzin po zakończeniu limitu lub powiadomic organizatora o rezygnacji lub powodzie opóźnienia.</li>
  <li> Uczestnicy mogą iść samotnie i w grupach, mniej doświadczonym polecamy unikanie trasy nocą samemu, ale też zachęcamy, by każdy choć kawałek przeszedł samotnie lub zmieniał ekipę z którą idzie.</li>
  <li> Strój należy dobrać wg własnych preferencji,  zalecamy i coś ciepłego na noc i coś przeciwdeszczowego, a także coś przeciwsłonecznego na dzień.</li>
  <li> Sprzęt zdecydowanie sugerowany:
    <ul type="disc">
    <li> Dowód osobisty lub paszport - szczególnie jeśli planuje się zahaczenie do Czech</li>
    <li> Telefon</li>
    <ul type="square">
      <li> Naładowany</li>
      <li> Aktywny</li>
      <li> Z zainstalowanymi aplikacjami meteo, mapa-turystyczna, e-podroznik i Ratunek</li>
    </ul>
    <li> latarka z zapasem baterii na jedną noc - nawet jeśli planowany jest nocleg</li>
    <li> Apteczka. Polecana zawartość</li>
    <ul type="square">
      <li> Plastry,  bandaże,  opaski elastyczne</li>
      <li> Środki przeciwbólowe, przeciw zatruciom, nospa</li>
      <li> Octenisept</li>
      <li> Filtr przeciwsłoneczny w przypadku słonecznej pogody</li>
    </ul>
    <li> Pojemnik na wodę o pojemności min. 1 litr</li>
    <li> Minimum 50zl w gotówce</li>
    <li> Polecamy wziąć ładowarkę do telefonu lub/i powerbank</li>
  </ul></li>
</ol></li>
<li> <b>Punktacja i wyniki</b>
  <ol type="a">
  <li> <b>Punkty dodatnie sportowe</b> (zaokrąglone do najbliższej wartości, weryfikowane po zawodach)
    <ul type="square">
      <li> Za każdy km po szlaku turystycznym (pieszym) 1 punkt</li>
      <li> Za kazde 100m podejscia -  0,75 pkt</li>
      <li> Za przejście przez miejsca punktowane -  X punktów  (wytłumaczenie dalej)</li>
    </ul>
  <li> <b>Punkty dodatnie bonusowe</b>
    <ul type="square">
      <li> Za każdą godzinę noclegu w schronisku - 3 punkty, maksymalnie 20 punktów (zachęta dla mniej doświadczonych piechurów, by zrobili sobie normalną nocną przerwę, ale też by nie trwała ona zbyt długo.)</li>
      <li> Za trasę wraz z dzieckiem poniżej 15 roku życia - przelicznik 1.25 za każdy kilometr i przewyższenie</li>
    </ul>
  <li> <b>Punkty dodatnie "artystyczne" - tutaj decyduje jury organizatorów</b>
    <ul type="square">
    <li> Za podjęcie i zakończenie sukcesem dodatkowego wyzwania losowanego na starcie - do 10 punktów
    <li> Za najlepszy wybór trasy (w sensie najciekaszej krajoznawczo) - trzy nagrody 10, 7, 5 punktow
    <li> Za najlepsze zdjęcie - kategoria panorama - 7, 5, 3 punkty
    <li> Za najlepsze zdjęcie w innych kategoriach - 5, 3, 1 punkt. Kategorie następujące:
    <ul type="disc">
      <li> Flora i fauna</li>
      <li> Skały i potoki</li>
      <li> Uczestnik na punkcie bonusowym</li>
      <li> Domy i schroniska</li>
      <li> Historia</li>
      </ul>
    <li> Jedna osoba może zdobyć najwyżej jedną nagrodę w danej kategorii</li>
    <li> Zdjęcie musi być zrobione podczas Krążownika, niedopuszczalne jest użycie zdjęć archiwalnych</li>
    <li> Jedno zdjęcie może być zgłoszone w maksymalnie dwóch kategoriach, ale w obu może zdobyć punkty</li>
    </ul>
  <li> <b>Punkty ujemne</b>
    <ul type="square">
      <li> Za każde 10 minut spóźnienia na metę - -1pkt</li>
    </ul>
  <li> W przypadku trasy poza szlakami wątpliwości będą rozstrzygane na niekorzyść uczestnika (np.  Kwestia przewyzszenia na odcinku)
  <li> Trasa będzie weryfikowana i podliczana z użyciem aplikacji mapa-turystyczna. Jeśli nie masz GPSa albo track będzie niekompletny, zaprezentuj trasę stworzoną na tym portalu. W takim przypadku powinieneś też wysłać jakieś zdjęcia uwiarygadniające Twój wybór trasy i godziny noclegu. Jeśli trasa biegła poza szlakiem, opisz w mailu którędy
  </ol>
<li> <b>Miejsca punktowane</b>
  <ol type="a">
  <li> Przed zawodami wytypowanych jest około 40 punktów za zdobycie których otrzymuje się dodatkowe punkty</li>
  <li> Wartość punktowa miejsc będzie częściowo zalezna od oddalenia od startu, częściowo losowana i opublikowana na godzinę przed startem. Wartość punktowa będzie od 3 do 10 punktów</li>
  <li> Będzie wybranych kilka punktów "hardcore" - bardzo oddalonych od startu, wartych zawsze 12 punktów</li>
  <li> Punkty będą wybierane wśród ciekawych, acz nie bardzo popularnych miejsc. Wszystko po to, by uczestnicy odkryli miejsca wcześniej im nieznane</li>
  <li> Punkty oraz ich rozmieszczenie na mapie zostanie podane najpóźniej 3 miesiące przed zawodami.</li>
  <li> Za bycie jedynym uczestnikiem, który był w danym punkcie otrzymuje się dodatkowe 5 punktów</li>
</ol></li>
<li> <b>Postanowienia końcówe</b>
  <ol type="a">
  <li> <b>Zawody odbędą się niezależnie od warunków pogodowych</b></li>
  <li> Regulamin może ulec zmianie do dnia 31.05.2019</li>
  <li> Interpretacja regulaminu należy do organizatora</li>
  <li> Organizator może startować w zawodach, ale nie będzie liczony do oficjalnej punktacji</li>
  <li> Wyniki zostaną ogłoszone w ciągu miesiąca od zakończenia zawodów</li>
  <li> Należy bezwzględnie przestrzegać regulaminu KPNu (czyli nie chodzimy nocą po parku - to jest w końcu park narodowy), zasad zachowania w lesie,  zakazu smiecenia i glosnego zachowania. Ogniska można palić tylko w wyznaczonych ku temu miejscach i przy zachowaniu pełnej ostrożności</li>
  <li> Należy bezwzględnie przestrzegać regulaminu czeskiego opowiednika KPN </li>
  <li> Wszystkie zdjęcia wysłane orgaznizatorom mogą być przez nich użyte w celach niekomercyjnych na stronie i w materiałach promocyjnych</li>
  <li> Dla zwycięzcy przeznaczona jest nagroda o wartości symbolicznej. Przewidziane też są inne nagrody dla uczestników.</li>
  <li> Z każdej edycji planujemy stworzyć fotoalbum z wybranymi zdjęcami </li>
  </ol>
</ol>

<h5> Warszawa, 2019</h5>

app/views/home/calc.html.erb
Tutaj będzie kalkulator możliwych punktów na trasę. Ale to trochę roboty, więc będzie później. Albo nie będzie w ogóle :P

app/views/home/index.html.erb
<h1>Krażownik 2019</h1>
<br/>

Zapraszam na imprezę górską w której możesz przejść <p style="font-size: 1.3em; text-decoration: underline; display: inline;">90 km w Karkonoszach</p>. Niezależnie od tego czy będzie świeciło słońce, wiał mocny wiatr czy padał deszcz, będziesz mógł przejść całe  <p style="font-size: 1.3em; text-decoration: underline; display: inline;">60 km w Rudawach Janowickich</p>. Chyba że jednak nie będziesz miał na to ochoty, a będziesz chciał przejść <p style="font-size: 1.3em; text-decoration: underline; display: inline;">45 km w Górach Kaczawskich</p> i porządnie się po drodze wyspać. Albo możesz pokazać że jesteś prawdziwym twardzielem, iść bez przerwy i zrobić <p style="font-size: 1.3em; text-decoration: underline; display: inline;">120 km w Izerach i Karkonoszach</p>. Albo nie, niczego nie musisz. Możesz siedzieć nawet cały weekend na starcie i pić piwo :)

<br/><br/>

<%= image_tag('kraz_1_tiny.jpg') %>

<br/><br/>

<p>
Krążownik jest imprezą bez ustalonej trasy. Bez sędziów, punktów kontrolnych, limitów czasowych. Niemalże. Jedyne co uczestnika ogranicza to start i meta, oraz czas na całość imprezy. Jak sobie uczestnik ten czas rozłoży, jaką trasą pójdzie - to zależy tylko i wyłacznie od jego woli
</p>
<p>
Krążownik jest dla ludzi. Bez numerów startowych, pomiarów czasu. Bez wielkiej rywalizacji, chyba że kogoś właśnie to kręci. Z imprezą na mecie, z ludźmi znającymi siebie po imieniu. Dlatego nie ma publicznych zapisów - chcesz wziąć udział, napisz na mój adres mailowy st.zawadzki@gmail.com i napisz, dlaczego chcesz wziąć udział w imprezie.
</p>

<p>
  Krążownik co roku będzie startował w innym miejscu. Byśmy pokrążyli w coraz to nowych miejscach. Edycja 2019 odbędzie się z Jeleniej Góry.
</p>

app/views/home/next.html.erb
<h1> Kotlina Jeleniogórska </h1>

Otoczona pasmami górskimi kotlina jest pełna wspaniałej przyrody i historycznych pozostałości. Można skupić się na zdobywaniu najwyższych gór, można też zwiedzać to, co pozostało z bogatej historii regionu. Można wyskoczyć na czeskie piwo, można zobaczyć skałki wspinaczkowe, można zwiedzić drugą największą polską tamę i zobaczyć czy Jędrek dalej siedzi na zamku Chojnik.
<br/>

<%= image_tag('sniezka.jpg') %>

app/views/home/organizer.html.erb
<h1>Irracjonalnie Maszerujący</h1>

<br/>
<br/>

<h3>Osoba kontaktowa:</h3>
<b>Stanisław Zawadzki</b> (krazownik.im@gmail.com)

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-dark">
    <div class="navbar-toggleable-xs" id="exCollapsingNavbar2">
       <%= render 'layouts/navigation_links' %>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<%= link_to 'Start', home_index_path, class: 'navbar-brand'  %>
<%= link_to 'Regulamin', home_about_path, class: 'navbar-brand'  %>
<%= link_to 'Porady', home_support_path, class: 'navbar-brand'  %>
<%= link_to 'Edycja 2019', home_next_path, class: 'navbar-brand'  %>
<%= link_to 'Kalkulator 2019', home_calc_path, class: 'navbar-brand'  %>
<%= link_to 'Organizator', home_organizer_path, class: 'navbar-brand'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Krazownik" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Krazownik" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>